### ISSUE TITLE
KeyError: 'revisions'

### ISSUE THREAD

**Issue by TheDanRussian** [Kenny2github/mw-api-client#3]
Traceback (most recent call last):
  File "wikibot.py", line 27, in <module>
    contents = sandbox.read()
  File "/home/root1/.local/lib/python3.5/site-packages/mw_api_client/page.py", line 136, in read
    data = tuple(data['query']['pages'].values())[0]['revisions'][0]
KeyError: 'revisions'

**Comment by Kenny2github** [comment]
This bug is fixed in the most recent prerelease version. A stable release will come soon.
